version: "3.8"

services:

  php:
    build:
      context: ./docker-images/php-8.1
    container_name: ragnoria-php
    expose:
      - 9000
    volumes:
      - ${WORKSPACE_DIR}:/var/www/
    ports:
      - "6001:6001"
    links:
      - db

  nginx:
    build:
      context: ./docker-images/nginx-1.22
    container_name: ragnoria-nginx
    volumes:
      - ./vhosts:/etc/nginx/templates
      - ${WORKSPACE_DIR}:/var/www/
    links:
      - php
    ports:
      - "80:80"

  db:
    build:
      context: ./docker-images/mysql-8.0
    container_name: ragnoria-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
